---
title       : Shiny app for prediciting miles per gallon
subtitle    : 
author      : 
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Introduction

* This presentation presents my Shiny app for the Data Products course's course project
* The app can be found [here](https://froys4000.shinyapps.io/sh_app/)

--- .class #id 

## Aim of the app

* The app uses the `mtcars` data set from R
* This is a data set of `r data(mtcars); nrow(mtcars)` cars
* One of the variables in the data set is miles per gallon (MPG)
* There `r ncol(mtcars)-1` other variables
* The aim is to use these variables to predict miles per gallon

---

## How does the app work?

* The app allows the user to select which variables to use as predictors
* Then it fits a linear model with those variables as predictors, and MPG as the outcome
* It also produces a pairs scatterplot for all the variables included in the model

---

## Example

For instance, if the user selects the horse power and transmission variables, then the program runs the following code

```{r}
summary(lm(mpg ~ hp + am, data=mtcars))
```






